// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RiskCaptureDefintion.Specifications.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ConversionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Conversion.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Conversion", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Conversion")))
            {
                RiskCaptureDefintion.Specifications.Features.ConversionFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Convert risk capture definition xml to json formatted for engine")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Conversion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void ConvertRiskCaptureDefinitionXmlToJsonFormattedForEngine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert risk capture definition xml to json formatted for engine", new string[] {
                        "mytag"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 5
 testRunner.Given("I have the following xml:", "<RiskCaptureDefinition policyLine=\"UK Motor\">\r\n  <Pages>\r\n    <Page name=\"Propose" +
                    "r\">\r\n      <GroupLayout>\r\n        <Row><Cell groupId=\"1\"/><Cell groupId=\"2\"/></R" +
                    "ow>\r\n        <Row><Cell groupId=\"3\"/><Cell groupId=\"4\"/></Row>\r\n      </GroupLay" +
                    "out>\r\n      <Groups>\r\n        <Group groupId=\"1\" name=\"Proposer Information\">\r\n " +
                    "         <Fields>\r\n            <Field fieldName=\"title\" name=\"Title\" type=\"dropd" +
                    "own\" required=\"true\" description=\"Proposer title\">\r\n              <Options>\r\n   " +
                    "             <Option value=\"Mr\"/>\r\n                <Option value=\"Mrs\"/>\r\n      " +
                    "        </Options>\r\n              <RiskItemSource riskItem=\"proposerTitle\"/>\r\n  " +
                    "          </Field>\r\n          </Fields>\r\n        </Group>\r\n        <Group groupI" +
                    "d=\"2\" name=\"Contact details\">\r\n          <Fields>\r\n          </Fields>\r\n        " +
                    "</Group>\r\n        <Group groupId=\"3\" name=\"Address\">\r\n          <Fields>\r\n      " +
                    "    </Fields>\r\n        </Group>\r\n        <Group groupId=\"4\" name=\"Additional inf" +
                    "ormation\">\r\n          <Fields>\r\n          </Fields>\r\n        </Group>\r\n      </G" +
                    "roups>\r\n    </Page>\r\n    <Page name=\"Driver\">\r\n      <GroupLayout>\r\n        <Row" +
                    "><Cell groupId=\"5\"/></Row>\r\n        <Row><Cell groupId=\"6\"/></Row>\r\n        <Row" +
                    "><Cell groupId=\"7\"/><Cell groupId=\"8\"/></Row>\r\n        <Row><Cell groupId=\"9\"/><" +
                    "Cell groupId=\"10\"/></Row>\r\n      </GroupLayout>\r\n      <Groups>\r\n        <Repeat" +
                    "ingGroup groupId=\"5\" name=\"Manage drivers\">\r\n          <Columns>\r\n            <C" +
                    "olumn name=\"#\" type=\"text\">\r\n              <IndexSource/>\r\n            </Column>" +
                    "\r\n            <Column name=\"Forename\" type=\"text\">\r\n              <RiskItemSourc" +
                    "e riskItem=\"driverForename\"/>\r\n            </Column>\r\n          </Columns>\r\n    " +
                    "      <Groups>\r\n            <Group groupId=\"6\" name=\"Driver information\">\r\n     " +
                    "         <Fields>\r\n                <Field fieldName=\"driver_title\" name=\"Title\" " +
                    "type=\"dropdown\" required=\"true\" description=\"Driver title\">\r\n                  <" +
                    "Options>\r\n                    <Option value=\"Mr\"/>\r\n                    <Option " +
                    "value=\"Mrs\"/>\r\n                  </Options>\r\n                  <RiskItemSource r" +
                    "iskItem=\"driverTitle\"/>\r\n                </Field>\r\n              </Fields>\r\n    " +
                    "        </Group>\r\n            <RepeatingGroup groupId=\"7\" name=\"Drivers claims\">" +
                    "\r\n              <Columns>\r\n                <Column name=\"#\" type=\"text\">\r\n      " +
                    "            <IndexSource/>\r\n                </Column>\r\n                <Column n" +
                    "ame=\"Type\" type=\"text\">\r\n                  <RiskItemSource riskItem=\"claimType\"/" +
                    ">\r\n                </Column>\r\n                <Column name=\"Date\" type=\"text\">\r\n" +
                    "                  <RiskItemSource riskItem=\"claimDate\"/>\r\n                </Colu" +
                    "mn>\r\n                <Column name=\"Cost\" type=\"text\">\r\n                  <RiskIt" +
                    "emSource riskItem=\"claimCost\"/>\r\n                </Column>\r\n              </Colu" +
                    "mns>\r\n              <Groups>\r\n                <Group groupId=\"9\" name=\"Claim\">\r\n" +
                    "                  <Fields>\r\n                    <Field fieldName=\"claim_type\" na" +
                    "me=\"Claim type\" type=\"dropdown\" required=\"true\" description=\"\">\r\n               " +
                    "       <Options>\r\n                        <Option value=\"Accident\"/>\r\n          " +
                    "              <Option value=\"Theft\"/>\r\n                      </Options>\r\n       " +
                    "               <RiskItemSource riskItem=\"claimType\"/>\r\n                    </Fie" +
                    "ld>\r\n                  </Fields>\r\n                </Group>\r\n              </Grou" +
                    "ps>\r\n            </RepeatingGroup>\r\n            <RepeatingGroup groupId=\"8\" name" +
                    "=\"Drivers convictions\">\r\n              <Columns>\r\n              </Columns>\r\n    " +
                    "          <Groups>\r\n                <Group groupId=\"10\" name=\"Conviction\">\r\n    " +
                    "              <Fields>\r\n                  </Fields>\r\n                </Group>\r\n " +
                    "             </Groups>\r\n            </RepeatingGroup>\r\n          </Groups>\r\n    " +
                    "    </RepeatingGroup>\r\n      </Groups>\r\n    </Page>\r\n  </Pages>\r\n</RiskCaptureDe" +
                    "finition>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 115
    testRunner.When("I convert the risk capture xml to json", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 116
    testRunner.Then("I should receive the following json:", "{\r\n    policyLine: \'UK Motor\',\r\n    pages: {\r\n        proposer: {\r\n            na" +
                    "me: \'Proposer\',\r\n            groupLayout: [\r\n                [ 1, 2 ],\r\n        " +
                    "        [ 3, 4 ]\r\n            ],\r\n            groups: [1, 2, 3, 4],\r\n           " +
                    " repeatingGroups: []\r\n        },\r\n        driver: {\r\n            name: \'Driver\'," +
                    "\r\n            groupLayout: [\r\n                [ 5 ],\r\n                [ 6 ],\r\n  " +
                    "              [ 7, 8 ],\r\n                [ 9, 10 ]\r\n            ],\r\n            " +
                    "groups: [],\r\n            repeatingGroups: [ 5 ]\r\n        }\r\n    },\n    groups: {" +
                    "\r\n      1: {\r\n        id: 1,\r\n        name: \'Proposer Information\',\r\n        col" +
                    "umns: [],\r\n        fields: [ 1 ],\r\n        subGroups: []\r\n      },\r\n      2: {\r\n" +
                    "        id: 2,\r\n        name: \'Contact details\',\r\n        columns: [],\r\n        " +
                    "fields: [],\r\n        subGroups: [],\r\n        subRepeatingGroups: []\r\n      },\r\n " +
                    "     3: {\r\n        id: 3,\r\n        name: \'Address\',\r\n        columns: [],\r\n     " +
                    "   fields: [],\r\n        subGroups: [],\r\n        subRepeatingGroups: []\r\n      }," +
                    "\r\n      4: {\r\n        id: 4,\r\n        name: \'Additional information\',\r\n        c" +
                    "olumns: [],\r\n        fields: [],\r\n        subGroups: [],\r\n        subRepeatingGr" +
                    "oups: []\r\n      },\r\n      5: {\r\n        id: 5,\r\n        name: \'Manage drivers\',\r" +
                    "\n        columns: [ 1, 2 ],\r\n        fields: [],\r\n        subGroups: [ 6 ],\r\n   " +
                    "     subRepeatingGroups: [ 7, 8 ]\r\n      },\r\n      6: {\r\n        id: 6,\r\n       " +
                    " name: \'Driver information\',\r\n        columns: [],\r\n        fields: [ 14 ],\r\n   " +
                    "     subGroups: [],\r\n        subRepeatingGroups: []\r\n      },\r\n      7: {\r\n     " +
                    "   id: 7,\r\n        name: \'Drivers claims\',\r\n        columns: [ 1, 9, 10, 11 ],\r\n" +
                    "        fields: [],\r\n        subGroups: [ 9 ],\r\n        subRepeatingGroups: []\r\n" +
                    "      },\r\n      8: {\r\n        id: 8,\r\n        name: \'Drivers convictions\',\r\n    " +
                    "    columns: [ 1, 12, 13 ],\r\n        fields: [],\r\n        subGroups: [ 10 ],\r\n  " +
                    "      subRepeatingGroups: []\r\n      },\r\n      9: {\r\n        id: 9,\r\n        name" +
                    ": \'Claim\',\r\n        columns: [],\r\n        fields: [ 18 ],\r\n        subGroups: []" +
                    ",\r\n        subRepeatingGroups: []\r\n      },\r\n      10: {\r\n        id: 10,\r\n     " +
                    "   name: \'Conviction\',\r\n        columns: [],\r\n        fields: [],\r\n        subGr" +
                    "oups: [],\r\n        subRepeatingGroups: []\r\n      }\r\n    }\n}", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
